---

resource_types:
  - name: docker-image
    type: registry-image
    source:
      repository: concourse/docker-image-resource

resources:
  - name: my-java-repo
    type: git
    source:
      uri: https://github.com/iamdatvt94/concourse-demo.git
      branch: main
  - name: gradle-image
    type: docker-image
    source:
      repository: gradle
      tag: "7.6-jdk17"

jobs:
  - name: build
    plan:
      - get: my-java-repo
        trigger: true
      - task: build-task
        file: my-java-repo/ci/build.yml

  - name: deploy
    plan:
      - get: my-java-repo
        trigger: true
        passed: [build]
      - task: deploy-task
        file: my-java-repo/ci/deploy.yml
